# Generated by Django 3.0.9 on 2022-11-17 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('examples', '0002_auto_20221117_1001'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='publication_date',
            new_name='clientcompany',
        ),
    ]
