# Generated by Django 3.0.9 on 2022-11-17 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('examples', '0003_auto_20221117_1004'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='price',
            new_name='clientemail',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='author',
            new_name='clientphone',
        ),
    ]
