# Generated by Django 3.0.9 on 2022-11-17 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examples', '0004_auto_20221117_1009'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectid', models.CharField(max_length=50)),
                ('projectname', models.CharField(max_length=50, null=True)),
                ('pages', models.IntegerField(blank=True, null=True)),
                ('Department', models.PositiveSmallIntegerField(choices=[(1, 'DevelopmentDepartment'), (2, 'ManagersDepartment'), (3, 'ApplicationDepartment'), (4, 'AccountsDepartments')])),
                ('priority', models.PositiveSmallIntegerField(choices=[(1, 'High'), (2, 'Medium'), (3, 'Low')])),
                ('client', models.PositiveSmallIntegerField(choices=[(1, 'client01'), (2, 'client02'), (3, 'client03')])),
                ('timestamp', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
