# Generated by Django 3.0.9 on 2022-11-17 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('examples', '0006_project_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='start_date',
        ),
    ]
