# Generated by Django 3.0.9 on 2022-11-17 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examples', '0007_remove_project_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='start_date',
            field=models.DateField(null=True),
        ),
    ]
