# Generated by Django 3.0.9 on 2022-11-17 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('examples', '0008_auto_20221117_1926'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='project',
            name='start_date',
        ),
    ]
