# Generated by Django 3.0.9 on 2022-11-17 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('examples', '0009_auto_20221117_1932'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='timestamp',
        ),
    ]
