# Generated by Django 3.0.9 on 2022-11-17 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('examples', '0011_project_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='gender',
        ),
    ]
