# Generated by Django 3.0.9 on 2022-11-17 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examples', '0012_remove_project_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='gender',
            field=models.CharField(choices=[('0', 'Female'), ('1', 'male')], max_length=11, null=True),
        ),
    ]
