# Generated by Django 3.0.9 on 2022-11-18 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('examples', '0013_project_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='gender',
        ),
    ]
