# Generated by Django 3.0.9 on 2022-11-18 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examples', '0014_remove_project_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='pages',
        ),
        migrations.AddField(
            model_name='project',
            name='gender',
            field=models.CharField(choices=[('0', 'Completed'), ('1', 'Pending'), ('1', 'On Progress')], max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='Department',
            field=models.CharField(choices=[('DevelopmentDepartment', 'DevelopmentDepartment'), ('ManagersDepartment', 'ManagersDepartment'), ('ApplicationDepartment', 'ApplicationDepartment'), ('AccountsDepartments', 'AccountsDepartments')], max_length=50),
        ),
        migrations.AlterField(
            model_name='project',
            name='client',
            field=models.CharField(choices=[('client01', 'client01'), ('client02', 'client02'), ('client03', 'client03')], default='green', max_length=19),
        ),
        migrations.AlterField(
            model_name='project',
            name='priority',
            field=models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], max_length=50),
        ),
    ]
