# Generated by Django 3.0.9 on 2022-11-18 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examples', '0015_auto_20221118_0955'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='gender',
        ),
        migrations.AddField(
            model_name='project',
            name='workstatus',
            field=models.CharField(choices=[('Completed', 'Completed'), ('Pending', 'Pending'), ('On Progress', 'On Progress')], default='Pending', max_length=11, null=True),
        ),
    ]
