# Generated by Django 3.0.9 on 2022-11-18 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examples', '0016_auto_20221118_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='workstatus',
            field=models.CharField(choices=[('Completed', 'Completed'), ('Pending', 'Pending'), ('OnProgress', 'OnProgress')], default='Pending', max_length=11, null=True),
        ),
    ]
