# Generated by Django 3.0.9 on 2022-11-18 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('examples', '0017_auto_20221118_1605'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='book_type',
        ),
        migrations.RemoveField(
            model_name='book',
            name='pages',
        ),
    ]
