# Generated by Django 3.0.9 on 2022-11-18 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examples', '0018_auto_20221118_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='clientemail',
            field=models.CharField(max_length=50),
        ),
    ]
